# Generated by Django 5.1.7 on 2025-08-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TextField(max_length=5),
        ),
    ]
